/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.locadoraapp;

import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class CadastroFilmeTela extends javax.swing.JFrame {

    /**
     * Creates new form CursosTela
     */
    public CadastroFilmeTela() {
        super("Locadora");
        initComponents();
        this.setLocationRelativeTo(null);//centraliza
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generoFilme2ComboBox = new javax.swing.JComboBox<>();
        voltarButton = new javax.swing.JButton();
        concluirButton = new javax.swing.JButton();
        nomeFilmeTextField = new javax.swing.JTextField();
        generoFilme1ComboBox = new javax.swing.JComboBox<>();
        anoFilmeSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 540));
        setPreferredSize(new java.awt.Dimension(460, 540));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 27, 134));
        jPanel1.setLayout(null);

        generoFilme2ComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        generoFilme2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o gênero secundário", "Romance", "Comédia", "Terror", "Suspense", "Ação" }));
        generoFilme2ComboBox.setBorder(null);
        generoFilme2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoFilme2ComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(generoFilme2ComboBox);
        generoFilme2ComboBox.setBounds(230, 320, 204, 40);

        voltarButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voltarButton);
        voltarButton.setBounds(50, 390, 170, 50);

        concluirButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        concluirButton.setText("Concluir Cadastro");
        concluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(concluirButton);
        concluirButton.setBounds(260, 390, 170, 51);
        concluirButton.getAccessibleContext().setAccessibleName("concluir");

        nomeFilmeTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nomeFilmeTextField.setToolTipText("");
        nomeFilmeTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomeFilmeTextField.setName(""); // NOI18N
        nomeFilmeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFilmeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeFilmeTextField);
        nomeFilmeTextField.setBounds(40, 110, 390, 40);

        generoFilme1ComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        generoFilme1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o gênero do filme", "Romance", "Comédia", "Terror", "Suspense", "Ação" }));
        generoFilme1ComboBox.setBorder(null);
        generoFilme1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoFilme1ComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(generoFilme1ComboBox);
        generoFilme1ComboBox.setBounds(230, 250, 204, 40);

        anoFilmeSpinner.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        anoFilmeSpinner.setModel(new javax.swing.SpinnerNumberModel(2000, 1878, null, 1));
        anoFilmeSpinner.setToolTipText("");
        anoFilmeSpinner.setBorder(null);
        jPanel1.add(anoFilmeSpinner);
        anoFilmeSpinner.setBounds(230, 180, 204, 40);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 80, 37, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastrar Filme");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(149, 15, 164, 32);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ano de lançamento:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 122, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gênero secundário (opcional):");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 320, 181, 40);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gênero do filme:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 260, 101, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja voltar?", "Aviso", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            AvaliarFilmeTela av = new AvaliarFilmeTela();
            av.setVisible(true);
            dispose();
        } 
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void concluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonActionPerformed
        String nomeFilme = nomeFilmeTextField.getText();
        int anoFilme = Integer.parseInt(anoFilmeSpinner.getValue().toString());
        String generoFilme1 = generoFilme1ComboBox.getSelectedItem().toString();
        String generoFilme2 = generoFilme2ComboBox.getSelectedItem().toString();


        if (generoFilme2.equals("Selecione um segundo gênero de filme favorito")) {
            generoFilme2 = null;
        }

        var filme = new Filme(nomeFilme, anoFilme, generoFilme1, generoFilme2);
        var dao = new DAO();

        if (nomeFilme.isEmpty() || nomeFilme.isBlank()) {
            JOptionPane.showMessageDialog(null, "O campo Nome não pode estar vazio");
        } else if (generoFilme1.equals(generoFilme2)) {
            JOptionPane.showMessageDialog(null, "Os campos de gênero do filme não podem ser iguais");
        } else {
            try {
                dao.cadastrarFilme(filme);
                JOptionPane.showMessageDialog(null, "Filme cadastrado com sucesso!");
                AvaliarFilmeTela av = new AvaliarFilmeTela();
                av.setVisible(true);
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro");
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_concluirButtonActionPerformed

    private void generoFilme2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoFilme2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoFilme2ComboBoxActionPerformed

    private void nomeFilmeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFilmeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFilmeTextFieldActionPerformed

    private void generoFilme1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoFilme1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoFilme1ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilmeTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anoFilmeSpinner;
    private javax.swing.JButton concluirButton;
    private javax.swing.JComboBox<String> generoFilme1ComboBox;
    private javax.swing.JComboBox<String> generoFilme2ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeFilmeTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
