/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.locadoraapp;

import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form CursosTela
     */
    public CadastroTela() {
        super("Locadora");
        initComponents();
        this.setLocationRelativeTo(null);//centraliza
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generosFilmeComboBox = new javax.swing.JComboBox<>();
        emailUsuarioTextField = new javax.swing.JTextField();
        idadeUsuarioTextField = new javax.swing.JTextField();
        generoUsuarioTextField = new javax.swing.JTextField();
        sairButton = new javax.swing.JButton();
        concluirButton = new javax.swing.JButton();
        RepitaSenha = new javax.swing.JPasswordField();
        Senha = new javax.swing.JPasswordField();
        nomeUsuarioTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro na Locadora"));

        generosFilmeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu gênero de filme favorito", "Romance", "Comédia", "Terror", "Suspense", "Ação" }));
        generosFilmeComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Gênero de filme favorito"));
        generosFilmeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generosFilmeComboBoxActionPerformed(evt);
            }
        });

        emailUsuarioTextField.setToolTipText("");
        emailUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        emailUsuarioTextField.setName(""); // NOI18N
        emailUsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioTextFieldActionPerformed(evt);
            }
        });

        idadeUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));

        generoUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));

        sairButton.setText("Voltar");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });

        concluirButton.setText("Concluir Cadastro");
        concluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonActionPerformed(evt);
            }
        });

        RepitaSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Repita a senha"));
        RepitaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepitaSenhaActionPerformed(evt);
            }
        });

        Senha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });

        nomeUsuarioTextField1.setToolTipText("");
        nomeUsuarioTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nomeUsuarioTextField1.setName(""); // NOI18N
        nomeUsuarioTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailUsuarioTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(concluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generosFilmeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RepitaSenha)
                    .addComponent(Senha)
                    .addComponent(nomeUsuarioTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generoUsuarioTextField)
                    .addComponent(idadeUsuarioTextField))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nomeUsuarioTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generoUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idadeUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generosFilmeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RepitaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        emailUsuarioTextField.getAccessibleContext().setAccessibleName("Nome");
        idadeUsuarioTextField.getAccessibleContext().setAccessibleName("Idade");
        generoUsuarioTextField.getAccessibleContext().setAccessibleName("Genero");
        concluirButton.getAccessibleContext().setAccessibleName("concluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        LoginTela lt = new LoginTela();
        lt.setVisible(true);
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void concluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonActionPerformed
        String nome = emailUsuarioTextField.getText();
        String generoUsuario = generoUsuarioTextField.getText();
        int idade = Integer.parseInt(idadeUsuarioTextField.getText());
        String generoFilmeFavorito = generosFilmeComboBox.getSelectedItem().toString();
        String email = emailUsuarioTextField.getText();
        String senha = new String(Senha.getPassword());
        String repitaSenha = new String(RepitaSenha.getPassword());
        var usuario = new Usuario(nome, generoUsuario, idade, email, senha, generoFilmeFavorito);
        var dao = new DAO();

        if (senha.equals(repitaSenha)) {
            try {
                dao.cadastrarUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "As senhas não batem");
        }

    }//GEN-LAST:event_concluirButtonActionPerformed

    private void generosFilmeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generosFilmeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generosFilmeComboBoxActionPerformed

    private void emailUsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuarioTextFieldActionPerformed

    private void RepitaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepitaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepitaSenhaActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void nomeUsuarioTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeUsuarioTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField RepitaSenha;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton concluirButton;
    private javax.swing.JTextField emailUsuarioTextField;
    private javax.swing.JTextField generoUsuarioTextField;
    private javax.swing.JComboBox<String> generosFilmeComboBox;
    private javax.swing.JTextField idadeUsuarioTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeUsuarioTextField1;
    private javax.swing.JButton sairButton;
    // End of variables declaration//GEN-END:variables
}
